tetratelabs/proxy-wasm-go-sdk

examples/helloworld/main.go, examples/http_auth_random/main.go, examples/http_headers/main.go, runtime/context.go, runtime/conv_tinygo.go, runtime/types/errors.go
=> convert status codes to Go errors

Makefile, e2e/e2e_test.go, examples/helloworld/envoy.yaml, examples/shared_queue/main.go
=> add e2e tests on examples

.github/workflows/workflow.yaml, Makefile, README.md, examples/helloworld/main.go, examples/http_auth_random/main.go, examples/http_headers/main.go, examples/metrics/main.go, examples/network/main.go, examples/shared_data/main.go, examples/shared_queue/main.go, examples/vm_plugin_configuration/main.go, proxywasm/hostcall_logging.go, proxywasm/hostcall_logging_test.go
resolves #44 
related to https://github.com/tetratelabs/getenvoy/pull/104
TODOs
=> use nightly TinyGo: WASI supported version

Makefile, e2e/e2e_test.go, examples/http_body/README.md, examples/http_body/envoy.yaml, examples/http_body/main.go, examples/http_body/main_test.go, proxytest/http.go, proxytest/proxytest.go, proxywasm/hostcall.go, proxywasm/rawhostcall/rawhostcall.go, proxywasm/rawhostcall/rawhostcall_mock.go
Resolve https://github.com/tetratelabs/proxy-wasm-go-sdk/issues/45
We've tested the `set buffer bytes` function deployed in Istio and it seems to be working as expected.
Filter built tiny go version:
```
tinygo version  
tinygo version 0.16.0-dev darwin/amd64 (using go version go1.15 and LLVM version 10.0.1)
```
Built using:
```
tinygo build -o ./filters/myfilter/filter.wasm -target=wasi -wasm-abi=generic ./myfilter.go
```
Istio version
```
istioctl version                                                                                                                
client version: 1.7.0
control plane version: 1.7.0
data plane version: 1.7.0 (10 proxies)
```
Example usage:
```GOLANG
body := []byte(`{ "data": "my new body" }`)
bufferData := &body[0]
res := …
```
=> feat: support proxy set buffer bytes

.github/workflows/workflow.yaml, Makefile, README.md
changes made:
- use `tinygo/tinygo-dev:latest` image for building examples
- that corresponds to the dev branch of tinygo
- add make targets for building examples with that docker image 
resolve #81
=> use tinygo/tinygo-dev image and add make target for building binaries with docker image

proxywasm/abi_lifecycle.go
The context maps were not cleared on done, which caused the filters to crash after sending a few requests, since they ran out of memory.
=> chore: correctly clear context when proxy is done

.github/workflows/workflow.yaml, README.md
ref:  https://github.com/tetratelabs/proxy-wasm-go-sdk/issues/88
=> update upstream envoy on ci

proxywasm/abi_lifecycle.go, proxywasm/abi_lifecycle_test.go, proxywasm/vmstate.go, proxywasm/vmstate_test.go, proxywasm/vmstate_test_export.go
The `contextToRootID` map was not cleared when proxy on done was called.
=> fix: cleanup contextToRootID map on proxy done and map name correction

examples/configuration_from_root/README.md, examples/configuration_from_root/envoy.yaml, examples/configuration_from_root/main.go, examples/configuration_from_root/main_test.go, proxywasm/vmstate.go
I would like to add this GetRootContextByID call, so that configuration stored in the root context can be read by the child context.
=> feat: add GetRootContextByID call

proxytest/root.go
As discussed in: https://github.com/tetratelabs/proxy-wasm-go-sdk/issues/95
This allows users to check the body for outgoing http requests in tests.
resolves  https://github.com/tetratelabs/proxy-wasm-go-sdk/issues/95
=> fix: add body to ProxyHttpCall return value

.github/workflows/workflow.yaml, Makefile, README.md
the container is yet to be pushed to dockerhub
=> Update for TinyGo 0.16.0 release

.github/workflows/workflow.yaml, README.md, examples/helloworld/main.go, proxytest/proxytest.go, proxywasm/hostcall.go, proxywasm/rawhostcall/rawhostcall.go, proxywasm/rawhostcall/rawhostcall_mock.go
Delete proxy_get_current_time_nanoseconds since time.Now is now available as of istio 1.8.1 and already in Envoy's upstream
=> Istio 1.8.1

examples/http_headers/main.go
=> Fix log typo in examples/http_headers

README.md, e2e/e2e_test.go, examples/configuration_from_root/main.go, examples/configuration_from_root/main_test.go, examples/http_auth_random/main.go, examples/http_auth_random/main_test.go, examples/http_body/main.go, examples/http_body/main_test.go, examples/http_headers/main.go, examples/http_headers/main_test.go, examples/metrics/main.go, examples/metrics/main_test.go, examples/network/main.go, examples/network/main_test.go, examples/shared_data/main.go, examples/shared_data/main_test.go, examples/shared_queue/main.go, examples/shared_queue/main_test.go, proxytest/option.go, proxytest/proxytest.go, proxywasm/abi_lifecycle.go, proxywasm/abi_lifecycle_test.go, proxywasm/context.go, proxywasm/vmstate.go, proxywasm/vmstate_test.go
This is kind of an improvement from #93 in favor of https://github.com/proxy-wasm/proxy-wasm-rust-sdk/pull/34 and https://github.com/proxy-wasm/proxy-wasm-rust-sdk/pull/67
Note that this is a breaking change, though the fix is trivial.
=> Have NewStreamContext and NewHttpContext in RootContext

proxywasm/abi_alloc.go
The symbol `malloc` collides with the one defined in wasi-libc, which causes the link error if we use some unhappy wasi functions
=> Use proxy_on_memory_allocate instead of malloc.

.github/workflows/workflow.yaml, README.md, e2e/e2e_test.go, examples/http_routing/README.md, examples/http_routing/envoy.yaml, examples/http_routing/main.go, examples/http_routing/main_test.go
=> Add canary routing example.

proxywasm/abi_lifecycle.go, proxywasm/abi_lifecycle_test.go, proxywasm/context.go
OnDone is called for each root context so VMDone is not accurate.
=> Rename OnVMDone to OnPluginDone

e2e/e2e_test.go, examples/foreign_call_on_tick/README.md, examples/foreign_call_on_tick/envoy.yaml, examples/foreign_call_on_tick/main.go, examples/foreign_call_on_tick/main_test.go, proxytest/root.go, proxywasm/hostcall.go, proxywasm/rawhostcall/rawhostcall.go, proxywasm/rawhostcall/rawhostcall_mock.go
recently,  i want to call the host function in my wasm,  i found there is a spec define this interface `proxy_call_foreign_function `
more info: https://github.com/proxy-wasm/spec/tree/master/abi-versions/vNEXT#foreign-function-interface-ffi
my wasm is written by golang, so i use this repo in my project, but it doesn't implement `proxy_call_foreign_function `, so i do this.
=> Add support for foreign functions.

proxywasm/serde.go
Remove the redundant map allocation.
=> Optimize map deserializer.

e2e/e2e_test.go, examples/http_body/README.md, examples/http_body/envoy.yaml, examples/http_body/main.go, examples/http_body/main_test.go, proxytest/http.go, proxytest/proxytest.go, proxywasm/hostcall.go
resolves #117 
Implemented the API by @pwoelfle https://github.com/tetratelabs/proxy-wasm-go-sdk/issues/117#issuecomment-789530828.
=> Add Append/Prepend/Replace buffers, and remove SetBuffer to disambiguate.

.github/workflows/workflow.yaml
=> Use Go 1.16.5 on CI

README.md, proxytest/http.go, proxytest/network.go, proxytest/proxytest.go, proxytest/root.go, proxywasm/abi_l7_test.go, proxywasm/abi_test_export.go, proxywasm/hostcall_logging_test.go, proxywasm/hostcall_metric_test.go, proxywasm/rawhostcall/rawhostcall_mock.go
=> doc: cleanup README, fix typo of WASM to Wasm.

README.md
Occasionally I forgot to update accordingly so now remove this from README.
=> Fix README.md: stop maintain Envoy/Istio/Proxy-Wasm Go SDK tags

.github/workflows/workflow.yaml, Makefile, examples/wasm-image.Dockerfile
resolves #200 and images should be available here [ghcr.io/tetratelabs/proxy-wasm-go-sdk-examples:${example name}](https://github.com/orgs/tetratelabs/packages/container/package/proxy-wasm-go-sdk-examples) as docker images
=> Push Wasm images of examples to ghcr.

.github/workflows/workflow.yaml
=> examples: only push images on the main branch.

examples/http_auth_random/main.go, examples/http_body/main.go, proxywasm/hostcall.go
=> Allow specifying gRPC status on SendHttpResponse.

e2e/e2e_test.go, examples/metrics/README.md
Following the change in the Envoy upstream: https://github.com/envoyproxy/envoy/pull/17357
=> test: use prometheus endpoint for metrics test.

proxywasm/hostcall.go
This prevents GetPropety/SetPropety calls from panic.
=> Check emptiness of path/data for property.

e2e/e2e_test.go, examples/metrics/README.md, examples/metrics/envoy.yaml, examples/metrics/main.go, examples/metrics/main_test.go
=> example: using prometheus tags in custom metrics

README.md
The upfront $ sign must be removed by hand if we use the pretty cut&paste function of the Markdown codeblocks.
=> remove $ sign for easy cut&paste

.github/workflows/workflow.yaml
1.10 and 1.9 have already reached EOL
=> ci: update Istio versions, drop 1.10, 1.9

examples/json_validation/Dockerfile, examples/json_validation/README.md
- Have Dockerfile copy plugin into filename plugin.wasm, otherwise it
doesn't work.
- Use raw.githubusercontent.com links instead of github.com ones that
return html and can't be applied directly.
=> Small fixes to JSON validation example

.github/workflows/workflow.yaml, e2e/main_test.go, examples/dispatch_call_on_tick/envoy.yaml, examples/foreign_call_on_tick/envoy.yaml, examples/helloworld/envoy.yaml, examples/http_auth_random/envoy.yaml, examples/http_body/envoy.yaml, examples/http_headers/envoy.yaml, examples/http_routing/envoy.yaml, examples/json_validation/envoy.yaml, examples/metrics/envoy.yaml, examples/network/envoy.yaml, examples/postpone_requests/envoy.yaml, examples/shared_data/envoy.yaml, examples/shared_queue/envoy.yaml, examples/vm_plugin_configuration/envoy.yaml
Also, drops the test target of 1.18 as it's reached EOL
=> ci: run e2e on Envoy 1.22

Makefile
=> Upgrade golangci-lint to 1.46.0

proxywasm/proxytest/http.go, proxywasm/proxytest/proxytest.go, proxywasm/proxytest/root.go
Similarly to envoy, convert header and trailer keys to lower-case.
This is particularly useful in Go given that the Go standard library
uses a different format to deal with case-insensitiveness requirement.
https://github.com/golang/go/blob/go1.18.3/src/net/http/header.go#L226-L229
=> fix(proxytest): make headers and trailers case-insensitive

.github/workflows/workflow.yaml
=> ci: adds Envoy 1.23 test

.github/workflows/workflow.yaml
Not a high priority change, just noticed that `actions/cache` still has some remnants from when it was caching examples, not just generic build cache.
Also added tinygo's build cache directory
=> Tweak definition of ci cache

Makefile, README.md, e2e/e2e_test.go, proxywasm/hostcall.go, proxywasm/internal/abi_callback_alloc.go, proxywasm/internal/abi_callback_configuration.go, proxywasm/internal/abi_callback_configuration_test.go, proxywasm/internal/abi_callback_l4.go, proxywasm/internal/abi_callback_l7.go, proxywasm/internal/abi_callback_lifecycle.go, proxywasm/internal/abi_callback_queue.go, proxywasm/internal/abi_callback_timers.go, proxywasm/internal/abi_callback_version.go, proxywasm/internal/timing_off.go, proxywasm/internal/timing_on.go, proxywasm/proxytest/timing_off_test.go, proxywasm/proxytest/timing_on_test.go, proxywasm/types/context.go
Fixes #326 
There's some reformatting and lint fixes because of using Go 1.19 to develop, let me know if I should revert them for this PR
=> Add build tag that prints timings of ABI method execution.

e2e/e2e_test.go, examples/properties/README.md, examples/properties/envoy.yaml, examples/properties/go.mod, examples/properties/go.sum, examples/properties/main.go, examples/properties/main_test.go, proxywasm/hostcall.go, proxywasm/proxytest/http.go, proxywasm/proxytest/http_test.go, proxywasm/proxytest/proxytest.go
This pull request addresses [Issue #250](https://github.com/tetratelabs/proxy-wasm-go-sdk/issues/250). It implements the `ProxyGetProperty` and `ProxySetProperty` methods in `proxytest` and stores properties in a map.
Do you have any concerns about potential race conditions for the map within the context of `proxytest`? Thank you.
=> test framework: Implement ProxyGetProperty and ProxySetProperty

e2e/e2e_test.go, examples/http_headers/README.md, examples/http_headers/envoy.yaml, examples/http_headers/go.mod, examples/http_headers/go.sum, examples/http_headers/main.go, examples/http_headers/main_test.go
In order to check on a basic `curl` command the execution of the wasm extension, the `http_headers` example now will add to the response a header based on the value of the argument and also a hardcoded header to check that is working even with an empty argument.
=> Adds headers based on argument for "http_headers" example

.github/workflows/push-wasm-images.yaml, .github/workflows/workflow.yaml
=> ci: upgrade TinyGo 0.26, drop EOL versions of Envoy/Istio

proxywasm/hostcall.go
This PR addresses #350 by noting that not all log format verbs are supported within tinygo at the time of writing. Adding the caveats as doc comments felt like the best place for them, as most common editor configurations will display doc comments inline or as a hover when using these functions.
There were also a few typos that appeared to be copy/paste errors, so those were cleaned up as well.
=> Update log descriptions

doc/OVERVIEW.md, proxywasm/hostcall.go
/kind cleanup
fix typo `ququeID->queueID`, `Therfore->Therefore` in `doc/OVERVIEW.md` and `proxywasm/hostcall.go`
Fixes #
NONE
=> fix typo: ququeID->queueID, Therfore->Therefore

properties/connection.go, properties/connection_test.go, properties/properties.go, properties/util.go, proxywasm/proxytest/option.go, proxywasm/proxytest/proxytest.go
part of #396 
This commit creates a new package named `properies` which hosts
helper functions extracted/refactored from https://github.com/boeboe/envoy-wasm-plugins/tree/main/print-properties
=> Adds `properties` package

properties/connection.go, properties/connection_test.go, properties/pilot.go, properties/pilot_test.go, properties/proxyconfig.go, properties/proxyconfig_test.go, properties/request.go, properties/request_test.go, properties/response.go, properties/response_test.go, properties/serialization.go, properties/serialization_test.go, properties/types.go, properties/types_test.go, properties/upstream.go, properties/upstream_test.go, properties/util.go, properties/util_test.go, properties/wasm.go, properties/wasm_test.go, properties/xsd.go, properties/xsd_test.go
Ported the work done in WASM plugins to expose the properties API.
-  Added all of the Getters in separate files
-  Added marshaling and marshaling functions in `serialization.go`
-  Added Istio and Envoy specific types in `types.go`
-  Added GetProperty<Type> functions in `utils.go`
-  Ported all documentation over
-  Adopted unit test input data reflecting real data (from an Istio based setup) 
TBD with @mathetake @jcchavezs @nacx 
- The `marshaling` and `unmarshaling` functions should not be exclusive to `properties` api, as they are essential for the shared data API between different plugins as well
- Some consideration might need to be taken on `Envoy` vs `Istio` specific logic, although this is now already cleanly separated in different files
=> New properties API completion

properties/connection.go, properties/pilot.go, properties/proxyconfig.go, properties/request.go, properties/response.go, properties/serialization.go, properties/serialization_test.go, properties/upstream.go, properties/wasm.go, properties/xsd.go
=> chore: simplify properties.

properties/pilot.go, properties/pilot_test.go, properties/types.go, properties/types_test.go, properties/wasm.go, properties/wasm_test.go
=> properties: ensures enum naming consistency

e2e/e2e_test.go, examples/multiple_dispatches/README.md, examples/network/main.go
Brings https://github.com/tetratelabs/proxy-wasm-go-sdk/pull/410 to the finish line. Fixes a few typos.
=> chore: fixes typos

examples/http_body/main.go, examples/http_body/main_test.go, proxywasm/proxytest/http.go, proxywasm/proxytest/http_test.go
Following https://github.com/tetratelabs/proxy-wasm-go-sdk/issues/414 discussion this PR tries to:
- Fix the emulator: providing to `ProxyOnRequestBody` and `ProxyOnResponseBody` the size of the whole body buffer, not of the individual chunk.
- Clarifies the buffering usage in `http_body` example.
- ~~Adds `http_body_chunk` example showing how to read chunk by chunk while buffering.~~ → See https://github.com/tetratelabs/proxy-wasm-go-sdk/pull/421
- ~~nit: https://github.com/tetratelabs/proxy-wasm-go-sdk/pull/410~~ → See https://github.com/tetratelabs/proxy-wasm-go-sdk/pull/419
- ~~upgrades support for latest envoy and istio/proxyv2~~ → See https://github.com/tetratelabs/proxy-wasm-go-sdk/pull/420
Tentatively closes https://github.com/tetratelabs/proxy-wasm-go-sdk/issues/414.
=> fix: body callbacks return the whole buffered body size

README.md
nottinygc has been archived in https://github.com/wasilibs/nottinygc/commit/ca4199a6466adb90e9b0a87578896ab2d4341ede
cc @anuraaga
=> Removes mention to nottinygc in REAMDE

README.md
the repository has been removed a few months ago.
=> Removes mention to Zig SDK

Makefile
This migrates the OCI image workflow to properly use the 
personal token less repository-scoped package. In doing so,
this change the destination repository name as in the patch.
=> ci: fixes the OCI image push

doc/OVERVIEW.md
hope this clarifies your question! @sanposhiho
=> doc: modifies the GC section

README.md
thanks @anuraaga for the good comment
=> Updates README to reflect the project direction
