- examples/http_auth_random/main.go
- examples/shared_queue/README.md
- examples/shared_queue/envoy.yaml
- examples/shared_queue/main.go
- runtime/abi_queue.go
- runtime/abi_timers.go
- runtime/hostcall.go
- runtime/rawhostcall/rawhostcall.go
- runtime/rawhostcall/rawhostcall_mock.go
- runtime/types/errors.go
- runtime/types/types.go
> implement shared-queue ABI wrappers and add its example

- examples/shared_data/README.md
- examples/shared_data/envoy.yaml
- examples/shared_data/main.go
- examples/shared_queue/main.go
- runtime/hostcall.go
- runtime/rawhostcall/rawhostcall.go
- runtime/rawhostcall/rawhostcall_mock.go
> implement shared KVS ABI wrapper

- examples/vm_plugin_configuration/README.md
- examples/vm_plugin_configuration/envoy.yaml
- examples/vm_plugin_configuration/main.go
> add read configuration examples

- examples/http_auth_random/main.go
- examples/metrics/main.go
- go.mod
- proxywasm/abI_l7_test.go
- proxywasm/abi_configuration_test.go
- proxywasm/abi_l4_test.go
- proxywasm/abi_l7.go
- proxywasm/abi_lifecycle.go
- proxywasm/abi_lifecycle_test.go
- proxywasm/abi_queue_test.go
- proxywasm/abi_timers_test.go
- proxywasm/context.go
- proxywasm/hostcall.go
- proxywasm/hostcall_logging.go
- proxywasm/hostcall_logging_test.go
- proxywasm/hostcall_metric.go
- proxywasm/hostcall_metric_test.go
- proxywasm/hostcall_test.go
- proxywasm/hostcall_utils_test.go
- proxywasm/hostcall_utls.go
- proxywasm/rawhostcall/rawhostcall_mock.go
- proxywasm/serde.go
- proxywasm/serde_test.go
- proxywasm/vmstate.go
- proxywasm/vmstate_test.go
https://github.com/tetratelabs/getenvoy/issues/101
> add unittest

- .github/CODEOWNERS
- README.md
- proxywasm/abi_configuration_test.go
- proxywasm/hostcall_utils_go.go
- proxywasm/hostcall_utils_tinygo.go
> add limitation docs

- Makefile
- README.md
- examples/network/main.go
- examples/network/main_test.go
- proxytest/README.md
- proxytest/base.go
- proxytest/base_test.go
- proxytest/network.go
- proxywasm/abi_l4.go
- proxywasm/abi_l4_test.go
- proxywasm/context.go
- proxywasm/types/types.go
> impl network filter's test framework

- examples/shared_data/main.go
- examples/shared_data/main_test.go
- examples/shared_queue/main.go
- examples/shared_queue/main_test.go
- proxytest/base.go
- proxytest/base_test.go
- proxytest/network.go
- proxytest/network_test.go
- proxytest/root.go
- proxytest/root_test.go
- proxywasm/abi_queue.go
> add shared queue/data framework

- README.md
- examples/metrics/main.go
- examples/metrics/main_test.go
- examples/network/main_test.go
- examples/shared_data/main_test.go
- examples/shared_queue/main_test.go
- examples/vm_plugin_configuration/main_test.go
- proxytest/base.go
- proxytest/base_test.go
- proxytest/network.go
- proxytest/network_test.go
- proxytest/root.go
- proxytest/root_test.go
> add metric test framework

- README.md
- examples/http_auth_random/main.go
- examples/http_auth_random/main_test.go
- examples/http_headers/main_test.go
- examples/metrics/main_test.go
- examples/network/main.go
- proxytest/base.go
- proxytest/http.go
- proxytest/http_test.go
- proxytest/network.go
- proxytest/root.go
- proxywasm/abi_l7.go
- proxywasm/abi_l7_test.go
- proxywasm/context.go
- proxywasm/hostcall.go
- proxywasm/hostcall_logging_test.go
- proxywasm/hostcall_metric_test.go
- proxywasm/hostcall_utils_go.go
- proxywasm/hostcall_utils_tinygo.go
- proxywasm/rawhostcall/rawhostcall.go
- proxywasm/serde.go
- proxywasm/serde_test.go
> http filter framework

- e2e/e2e_test.go
- examples/http_auth_random/main_test.go
- examples/network/main.go
- examples/network/main_test.go
- proxytest/http.go
- proxytest/network.go
> connection counter on network filter example

- e2e/e2e_test.go
- examples/network/README.md
- examples/network/main.go
- proxywasm/hostcall.go
- proxywasm/rawhostcall/rawhostcall.go
- proxywasm/rawhostcall/rawhostcall_mock.go
- proxywasm/serde.go
- proxywasm/serde_test.go
> add get/set property

- .github/workflows/workflow.yaml
- Makefile
- README.md
- e2e/Dockerfile
- e2e/e2e_test.go
- examples/docker-compose.yml
- examples/helloworld/envoy.yaml
- examples/http_auth_random/envoy.yaml
- examples/http_headers/envoy.yaml
- examples/metrics/envoy.yaml
- examples/network/envoy.yaml
- examples/shared_data/envoy.yaml
- examples/shared_queue/envoy.yaml
- examples/vm_plugin_configuration/envoy.yaml
- go.mod
- proxywasm/abi_version.go
> update proxy_abi_version to support istio/proxyv2

- README.md
> release v0.0.3

- .github/workflows/workflow.yaml
- Makefile
- e2e/Dockerfile
> use getenvoy org's image for ci

- README.md
> release v0.0.4

- .github/workflows/workflow.yaml
- e2e/Dockerfile
> e2e on istio 1.7.3

- Makefile
- examples/helloworld/README.md
- examples/http_auth_random/README.md
- examples/http_headers/README.md
- examples/http_headers/main.go
- examples/http_headers/main_test.go
- examples/metrics/README.md
- examples/network/README.md
- examples/network/main.go
- examples/shared_data/README.md
- examples/shared_queue/README.md
- examples/vm_plugin_configuration/README.md
> cleanup examples

- .github/workflows/workflow.yaml
- Makefile
- examples/http_auth_random/main.go
- examples/http_auth_random/main_test.go
- examples/network/main_test.go
> fix: SDK test CI

- README.md
- examples/http_auth_random/main.go
- examples/http_headers/main.go
- examples/metrics/main.go
- examples/network/main.go
- examples/shared_data/main.go
- examples/shared_queue/main.go
- proxytest/option.go
- proxywasm/abi_lifecycle_test.go
- proxywasm/vmstate.go
- proxywasm/vmstate_test.go
> pass rootContextID to new{http,stream}Context

- Makefile
- README.md
- examples/helloworld/main_test.go
- examples/shared_queue/main_test.go
- proxytest/README.md
- proxytest/http.go
- proxytest/network.go
- proxytest/proxytest.go
- proxytest/root.go
> internal fix of proxytest / enhance docs

- Makefile
- README.md
- e2e/e2e_test.go
- examples/helloworld/main.go
- examples/helloworld/main_test.go
> fix examples

- README.md
- proxywasm/abi_version_010.go
https://github.com/tetratelabs/getenvoy/issues/101
https://github.com/tetratelabs/getenvoy/pull/104
> support envoy-wasm's release/v1.15.0 branch with 'abi_0_1_0' tag

- examples/helloworld/main.go
- examples/http_auth_random/main.go
- examples/http_headers/main.go
- examples/metrics/main.go
- examples/network/main.go
- examples/shared_data/main.go
- examples/shared_queue/main.go
- proxywasm/hostcall.go
> name parameters in examples

- .github/workflows/workflow.yaml
> gha: trigger on PRs

- .github/workflows/workflow.yaml
- README.md
> e2e on envoy upstream

- .github/workflows/workflow.yaml
- Makefile
- README.md
- examples/helloworld/envoy.yaml
- examples/http_auth_random/envoy.yaml
- examples/http_body/envoy.yaml
- examples/http_headers/envoy.yaml
- examples/metrics/envoy.yaml
- examples/network/envoy.yaml
- examples/shared_data/envoy.yaml
- examples/shared_queue/envoy.yaml
- examples/vm_plugin_configuration/envoy.yaml
> update upstream envoy on ci

- .github/workflows/workflow.yaml
- README.md
> Istio 1.8.0

- e2e/e2e_test.go
- examples/access_logger/envoy.yaml
- examples/access_logger/main.go
- examples/access_logger/main_test.go
- examples/helloworld/main_test.go
- examples/http_headers/main.go
- proxytest/http.go
- proxytest/network.go
- proxytest/proxytest.go
- proxytest/root.go
- proxywasm/abi_lifecycle.go
- proxywasm/abi_lifecycle_test.go
- proxywasm/abi_test_export.go
- proxywasm/context.go
- proxywasm/hostcall_lifecycle.go
> Add on_log inteface, and impl on_delete

- .github/workflows/workflow.yaml
- README.md
> Release 0.0.13

- proxywasm/abi_version_010.go
> allow abi 0.1.0

- e2e/e2e_test.go
- examples/dispatch_call_on_tick/README.md
- examples/dispatch_call_on_tick/envoy.yaml
- examples/dispatch_call_on_tick/main.go
- examples/dispatch_call_on_tick/main_test.go
- proxytest/http.go
- proxytest/network.go
- proxytest/proxytest.go
- proxytest/root.go
- proxywasm/abi_l7_test.go
- proxywasm/vmstate.go
- proxywasm/vmstate_test.go
> Fix nil pointer during http call dispatch on RootContexts

- .github/workflows/workflow.yaml
- Makefile
- README.md
> Test against Envoy 1.17.0

- .github/workflows/workflow.yaml
- Makefile
> Update TinyGo to 0.17

- .github/workflows/workflow.yaml
- README.md
> Add Istio and Envoy versions

- README.md
- examples/configuration_from_root/main_test.go
- examples/http_auth_random/main_test.go
- examples/http_body/main_test.go
- examples/http_headers/main_test.go
- examples/metrics/main_test.go
- examples/network/main_test.go
- examples/shared_data/main_test.go
- examples/shared_queue/main_test.go
- proxytest/http.go
- proxytest/network.go
- proxytest/proxytest.go
> Refactor API of proxytest framework.

- README.md
- examples/configuration_from_root/main.go
- examples/dispatch_call_on_tick/main.go
- examples/helloworld/main.go
- examples/metrics/main.go
- examples/network/main.go
- examples/shared_data/main.go
- examples/shared_queue/main.go
- examples/vm_plugin_configuration/main.go
- proxywasm/abi_configuration.go
- proxywasm/abi_configuration_test.go
- proxywasm/abi_test_export.go
- proxywasm/context.go
- proxywasm/types/enums.go
> Have OnPluginStartStatus and OnVMStartStatus

- examples/access_logger/main.go
- examples/access_logger/main_test.go
- examples/configuration_from_root/main.go
- examples/configuration_from_root/main_test.go
- examples/dispatch_call_on_tick/main.go
- examples/dispatch_call_on_tick/main_test.go
- examples/helloworld/main.go
- examples/helloworld/main_test.go
- examples/http_auth_random/main.go
- examples/http_auth_random/main_test.go
- examples/http_body/main.go
- examples/http_body/main_test.go
- examples/http_headers/main.go
- examples/http_headers/main_test.go
- examples/metrics/main.go
- examples/metrics/main_test.go
- examples/network/main.go
- examples/network/main_test.go
- examples/shared_data/main.go
- examples/shared_data/main_test.go
- examples/shared_queue/main.go
- examples/shared_queue/main_test.go
- examples/vm_plugin_configuration/main.go
- examples/vm_plugin_configuration/main_test.go
- proxytest/http.go
- proxytest/network.go
- proxytest/proxytest.go
- proxytest/root.go
- proxywasm/types/enums.go
> Refactor proxytest

- .github/workflows/workflow.yaml
- README.md
> release v0.1.0

- examples/http_auth_random/main.go
- proxywasm/hostcall.go
- proxywasm/hostcall_metric.go
> Update the signature of SendHttpResponse

- .github/workflows/workflow.yaml
> Use make cmd on ci

- proxywasm/hostcall.go
- proxywasm/types/enums.go
> Add {Close,Continue}{Up,Down}Stream.

- proxywasm/hostcall.go
> Add Set{Down,Up}streamData.

- examples/shared_queue/main.go
- examples/shared_queue/main_test.go
- proxytest/root.go
> use OnQueueReady in shared_queue example.

- .github/workflows/workflow.yaml
- Makefile
> Simplify GHA and fix Makefile.

- examples/foreign_call_on_tick/main.go
- examples/foreign_call_on_tick/main_test.go
- examples/http_auth_random/main.go
- proxytest/proxytest.go
- proxytest/root.go
> Refactor foreign function test.

- .github/workflows/workflow.yaml
- README.md
- examples/foreign_call_on_tick/README.md
> Test on Istio 1.10.

- .github/workflows/workflow.yaml
- e2e/e2e_test.go
- examples/access_logger/envoy.yaml
- examples/dispatch_call_on_tick/main.go
- examples/foreign_call_on_tick/README.md
- examples/foreign_call_on_tick/main.go
- examples/foreign_call_on_tick/main_test.go
- examples/http_body/envoy.yaml
- examples/http_body/main.go
resolves https://github.com/tetratelabs/proxy-wasm-go-sdk/issues/146
> Deflake e2e tests. 

- e2e/e2e_test.go
- examples/shared_data/main.go
> Deflake shared_data E2E.

- e2e/e2e_test.go
- e2e/main_test.go
> Refactor E2E.

- .github/workflows/workflow.yaml
- examples/http_body/README.md
- examples/network/main.go
- proxywasm/abi_l4_test.go
- proxywasm/hostcall.go
> Update TinyGo to 0.18

- e2e/e2e_test.go
- examples/access_logger/envoy.yaml
- examples/configuration_from_root/envoy.yaml
- examples/dispatch_call_on_tick/envoy.yaml
- examples/foreign_call_on_tick/envoy.yaml
- examples/helloworld/envoy.yaml
- examples/http_auth_random/envoy.yaml
- examples/http_body/envoy.yaml
- examples/http_headers/envoy.yaml
- examples/http_routing/envoy.yaml
- examples/metrics/envoy.yaml
- examples/network/envoy.yaml
- examples/shared_data/envoy.yaml
- examples/shared_queue/envoy.yaml
- examples/vm_plugin_configuration/envoy.yaml
> Cleaned up envoy.yaml.

- proxywasm/hostcall.go
> Add more comment on SendHttpResponse.

- README.md
- examples/dispatch_call_on_tick/main.go
- examples/foreign_call_on_tick/main.go
- examples/helloworld/main.go
- examples/http_auth_random/main.go
- examples/http_body/main.go
- examples/http_headers/main.go
- examples/http_routing/main.go
- examples/metrics/main.go
- examples/network/main.go
- examples/shared_data/main.go
- examples/shared_queue/receiver/main.go
- examples/shared_queue/sender/main.go
- examples/vm_plugin_configuration/main.go
- proxywasm/hostcall.go
- proxywasm/hostcall_logging.go
- proxywasm/hostcall_metric.go
- proxywasm/hostcall_metric_test.go
- proxywasm/internal/abi_callback_l7.go
- proxywasm/internal/vmstate.go
- proxywasm/proxytest/proxytest.go
- proxywasm/types/context.go
> Complete the doc comment for all exported API.

- README.md
> doc: Add instruction for standalone projects.

- .github/workflows/latestenvoy.yaml
following https://github.com/envoyproxy/envoy/pull/17280
> Run Envoy latest on e2e.

- examples/http_body/main.go
- examples/shared_queue/receiver/main.go
- examples/shared_queue/sender/main.go
- examples/vm_plugin_configuration/main.go
- proxywasm/hostcall.go
Following Rust SDK: https://github.com/proxy-wasm/proxy-wasm-rust-sdk/blob/abd0f5437212e5fd3dd6a70eac3959934278e643/src/traits.rs#L223
> Not require size in Get{Plugin,VM}Configuration.

- e2e/e2e_test.go
- examples/dispatch_call_on_tick/envoy.yaml
- examples/dispatch_call_on_tick/main.go
- examples/dispatch_call_on_tick/main_test.go
- proxywasm/internal/abi_callback_timers.go
> fix: call setActiveContext in onTick.

- .github/workflows/push-wasm-images.yaml
- .github/workflows/workflow.yaml
> Fix e2e cache failure.

- .github/workflows/workflow.yaml
> e2e: update Envoy versions.

- .github/workflows/workflow.yaml
- go.mod
- go.sum
> Update Go version in go.mod.

- proxywasm/proxytest/http.go
> proxytest: fix the behavior for empty header.

- .github/workflows/push-wasm-images.yaml
- .github/workflows/workflow.yaml
> Update TinyGo to 0.21.0

- README.md
> Add the ref to func-e in README.md.

- .github/workflows/workflow.yaml
- examples/postpone_requests/README.md
- examples/postpone_requests/main.go
> Add Istio 1.12 in End-to-End test matrix.

- README.md
> Specify the Go 1.17+ requirement.

- proxywasm/hostcall.go
> Fix wrong path size for SetProperty

- examples/helloworld/main.go
> Create default Http context in Hello world example.

- proxywasm/internal/abi_enums.go
- proxywasm/types/types.go
Use proper message instead of "unknown status code: 12".
> Clarify the unimplemented error

- .github/workflows/workflow.yaml
Ref: https://github.com/tetratelabs/proxy-wasm-go-sdk/pull/151#discussion_r791745003
> ci: comment why passing CGO=disabled explicitly

- .github/workflows/push-wasm-images.yaml
- .github/workflows/workflow.yaml
> Update TinyGo to 0.22.0

- .github/workflows/workflow.yaml
> ci: add Istio 1.13 e2e test

- .github/workflows/workflow.yaml
- Makefile
- examples/dispatch_call_on_tick/envoy.yaml
- examples/foreign_call_on_tick/envoy.yaml
- examples/helloworld/envoy.yaml
- examples/http_auth_random/envoy.yaml
- examples/http_body/envoy.yaml
- examples/http_headers/envoy.yaml
- examples/http_routing/envoy.yaml
- examples/metrics/envoy.yaml
- examples/network/envoy.yaml
- examples/postpone_requests/envoy.yaml
- examples/shared_data/envoy.yaml
- examples/shared_queue/envoy.yaml
- examples/vm_plugin_configuration/envoy.yaml
> Build each example in its dir

- .github/workflows/push-wasm-images.yaml
- Makefile
> Fix OCI image build

- proxywasm/internal/abi_callback_l7.go
- proxywasm/internal/abi_callback_l7_test.go
> Do not call callbacks for deleted contexts.

- .github/workflows/push-wasm-images.yaml
- .github/workflows/workflow.yaml
- proxywasm/proxytest/proxytest.go
> Upgrade TinyGo to 0.23

- .github/workflows/push-wasm-images.yaml
- .github/workflows/workflow.yaml
- Makefile
- examples/json_validation/go.mod
- examples/json_validation/go.sum
- go.mod
- go.sum
> build: polishes and version updates

- examples/dispatch_call_on_tick/go.mod
- examples/dispatch_call_on_tick/go.sum
- examples/foreign_call_on_tick/go.mod
- examples/foreign_call_on_tick/go.sum
- examples/helloworld/go.mod
- examples/helloworld/go.sum
- examples/http_auth_random/go.mod
- examples/http_auth_random/go.sum
- examples/http_body/go.mod
- examples/http_body/go.sum
- examples/http_headers/go.mod
- examples/http_headers/go.sum
- examples/http_routing/go.mod
- examples/http_routing/go.sum
- examples/json_validation/go.mod
- examples/json_validation/go.sum
- examples/metrics/go.mod
- examples/metrics/go.sum
- examples/network/go.mod
- examples/network/go.sum
- examples/postpone_requests/go.mod
- examples/postpone_requests/go.sum
- examples/shared_data/go.mod
- examples/shared_data/go.sum
- examples/shared_queue/go.mod
- examples/shared_queue/go.sum
- examples/vm_plugin_configuration/go.mod
- examples/vm_plugin_configuration/go.sum
> Update yaml.v3 dep in examples

- go.mod
- go.sum
> Update yaml.v3 dep

- .github/workflows/workflow.yaml
> ci: adds Istio 1.14

- examples/http_headers/go.sum
- examples/http_headers/main_test.go
- proxywasm/proxytest/http.go
- proxywasm/proxytest/proxytest.go
Superseeds https://github.com/tetratelabs/proxy-wasm-go-sdk/pull/283
> Adds response headers test

- .github/workflows/push-wasm-images.yaml
- .github/workflows/workflow.yaml
> TinyGo 0.24.0

- e2e/e2e_test.go
- examples/multiple_dispatches/README.md
- examples/multiple_dispatches/envoy.yaml
- examples/multiple_dispatches/go.mod
- examples/multiple_dispatches/go.sum
- examples/multiple_dispatches/main.go
- proxywasm/proxytest/proxytest.go
> example: multiple dispatches

- examples/multiple_dispatches/main_test.go
> Adds main_test.go for multiple dispatches example

- .github/workflows/push-wasm-images.yaml
- .github/workflows/workflow.yaml
- README.md
- examples/dispatch_call_on_tick/go.mod
- examples/foreign_call_on_tick/go.mod
- examples/helloworld/go.mod
- examples/http_auth_random/go.mod
- examples/http_body/go.mod
- examples/http_headers/go.mod
- examples/http_routing/go.mod
- examples/json_validation/go.mod
- examples/metrics/go.mod
- examples/multiple_dispatches/go.mod
- examples/network/go.mod
- examples/postpone_requests/go.mod
- examples/shared_data/go.mod
- examples/shared_queue/go.mod
- examples/vm_plugin_configuration/go.mod
- go.mod
> Update Go to 1.18 in examples

- Makefile
> Upgrade golangci-lint, goimports

- e2e/e2e_test.go
- examples/network/envoy.yaml
- examples/network/main.go
- proxywasm/hostcall.go
- proxywasm/proxytest/proxytest.go
> Adds support for map-typed metadata 

- Makefile
- doc/OVERVIEW.md
- examples/dispatch_call_on_tick/main_test.go
- examples/foreign_call_on_tick/main_test.go
- examples/helloworld/main_test.go
- examples/http_auth_random/main_test.go
- examples/http_body/main_test.go
- examples/http_headers/main_test.go
- examples/http_routing/main_test.go
- examples/json_validation/main_test.go
- examples/metrics/main_test.go
- examples/multiple_dispatches/main_test.go
- examples/network/main_test.go
- examples/postpone_requests/main_test.go
- examples/shared_data/main_test.go
- examples/vm_plugin_configuration/main_test.go
- proxywasm/internal/abi_callback_test_export.go
- proxywasm/internal/abi_hostcalls_mock.go
> Removes "proxytest" build tag completely

- .github/workflows/push-wasm-images.yaml
- .github/workflows/workflow.yaml
- e2e/main_test.go
> TinyGo 0.25.0

- proxywasm/proxytest/http.go
- proxywasm/proxytest/http_test.go
- Don't buffer request body when action is continue
- Buffer response body when action is pause
> Fix buffering of bodies in proxytest

- .github/workflows/workflow.yaml
> ci: adds Istio 1.15.0

- proxywasm/proxytest/timing_on_test.go
I guess my hypothesis that 0s is unfeasible is wrong...
https://github.com/tetratelabs/proxy-wasm-go-sdk/actions/runs/3102580430/jobs/5025021859
> Add sleep to timing test plugin to avoid sporadically logging 0s

- proxywasm/internal/abi_callback_configuration_test.go
This came to mind in #327 but wasn't sure about it so figured a separate PR is better
>  Rename Test_onVmStart to Test_pluginInitialization

- Makefile
running specific example re-added
> restores build.example target in Makefile

- .github/workflows/workflow.yaml
> ci: adds Envoy 1.24

- .github/workflows/workflow.yaml
> ci: adds Istio 1.16

- .github/workflows/push-wasm-images.yaml
- .github/workflows/workflow.yaml
> ci: update TinyGo to 0.27

- README.md
> doc: add reference to nottinygc
